// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mqxuflkdwndqqphzgyyq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1xeHVmbGtkd25kcXFwaHpneXlxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU1MDM5NTUsImV4cCI6MjA3MTA3OTk1NX0.QfB-Yndbg-MnjMxuLXnRve2oPRiENGQfu-iCGmvxiG0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});